export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CART_IS_OPEN: 'SET_CART_IS_OPEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART', 
    SELECTED_ITMES_NUMBER: 'SELECTED_ITMES_NUMBER',
    SET_TOTAL: 'SET_TOTAL',
}